const { execFileSync } = require('child_process');
const fs = require('fs/promises');
const fsSync = require('fs');
const path = require('path');

const HOOK_NAME = 'post-checkout';
const PACKAGE_ROOT = path.resolve(__dirname, '..');
const LINK_SCRIPT = path.join(PACKAGE_ROOT, 'link-untracked.cjs');
const ZERO_REV = '0000000000000000000000000000000000000000';

function runGit(args, cwd) {
    return execFileSync('git', args, {
        cwd,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe']
    }).trim();
}

function tryGit(args, cwd) {
    try {
        return runGit(args, cwd);
    } catch {
        return '';
    }
}

function isGitWorkTree(cwd) {
    return tryGit(['rev-parse', '--is-inside-work-tree'], cwd) === 'true';
}

function shellQuote(value) {
    return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function resolveHooksPath(hooksPath, repoRoot, commonGitDir) {
    if (!hooksPath) {
        return path.join(commonGitDir, 'hooks');
    }

    if (path.isAbsolute(hooksPath)) {
        return hooksPath;
    }

    return path.resolve(repoRoot, hooksPath);
}

function samePath(a, b) {
    return path.resolve(a) === path.resolve(b);
}

function hookBody({ nodePath, linkScript, previousHook }) {
    return `#!/bin/sh
# Generated by worktree-deps-autolink. Manual changes may be overwritten.

old_rev="$1"
checkout_type="$3"
zero_rev=${shellQuote(ZERO_REV)}
status=0

if [ "$checkout_type" = "1" ] && [ "$old_rev" = "$zero_rev" ] && [ "$WORKTREE_DEPS_AUTOLINK" != "0" ]; then
  if [ -f ${shellQuote(linkScript)} ]; then
    ${shellQuote(nodePath)} ${shellQuote(linkScript)} || status=$?
  else
    echo "worktree-deps-autolink: missing script ${linkScript}" >&2
    status=1
  fi
fi

previous_hook=${shellQuote(previousHook)}
if [ -n "$previous_hook" ] && [ -x "$previous_hook" ] && [ "$previous_hook" != "$0" ]; then
  "$previous_hook" "$@"
fi

exit "$status"
`;
}

async function install({ cwd, quiet = false } = {}) {
    if (process.env.WORKTREE_DEPS_AUTOLINK === '0') {
        if (!quiet) console.log('worktree-deps-autolink disabled by WORKTREE_DEPS_AUTOLINK=0');
        return;
    }

    const targetCwd = cwd || process.cwd();
    if (!isGitWorkTree(targetCwd)) {
        if (!quiet) console.log('worktree-deps-autolink: not inside a Git worktree, skipped');
        return;
    }

    const repoRoot = runGit(['rev-parse', '--show-toplevel'], targetCwd);
    const commonGitDir = path.resolve(repoRoot, runGit(['rev-parse', '--git-common-dir'], repoRoot));
    const managedRoot = path.join(commonGitDir, 'worktree-deps-autolink');
    const hooksDir = path.join(managedRoot, '_');
    const hookPath = path.join(hooksDir, HOOK_NAME);
    const previousHooksPath = tryGit(['config', '--get', 'core.hooksPath'], repoRoot);
    const previousHooksDir = resolveHooksPath(previousHooksPath, repoRoot, commonGitDir);
    const previousHook = samePath(previousHooksDir, hooksDir) ? '' : path.join(previousHooksDir, HOOK_NAME);

    await fs.mkdir(hooksDir, { recursive: true });
    await fs.writeFile(
        path.join(managedRoot, 'config.json'),
        JSON.stringify({
            previousHooksPath: previousHooksPath || null,
            previousHook: previousHook || null,
            installedAt: new Date().toISOString()
        }, null, 2)
    );
    await fs.writeFile(hookPath, hookBody({
        nodePath: process.execPath,
        linkScript: LINK_SCRIPT,
        previousHook
    }));
    await fs.chmod(hookPath, 0o755);

    runGit(['config', 'core.hooksPath', hooksDir], repoRoot);

    if (!quiet) {
        console.log(`worktree-deps-autolink installed: core.hooksPath=${hooksDir}`);
    }
}

async function uninstall({ cwd, quiet = false } = {}) {
    const targetCwd = cwd || process.cwd();
    if (!isGitWorkTree(targetCwd)) {
        if (!quiet) console.log('worktree-deps-autolink: not inside a Git worktree, skipped');
        return;
    }

    const repoRoot = runGit(['rev-parse', '--show-toplevel'], targetCwd);
    const commonGitDir = path.resolve(repoRoot, runGit(['rev-parse', '--git-common-dir'], repoRoot));
    const managedRoot = path.join(commonGitDir, 'worktree-deps-autolink');
    const hooksDir = path.join(managedRoot, '_');
    const currentHooksPath = tryGit(['config', '--get', 'core.hooksPath'], repoRoot);
    const currentHooksDir = resolveHooksPath(currentHooksPath, repoRoot, commonGitDir);

    if (samePath(currentHooksDir, hooksDir)) {
        const configPath = path.join(managedRoot, 'config.json');
        let previousHooksPath = '';

        if (fsSync.existsSync(configPath)) {
            try {
                previousHooksPath = JSON.parse(await fs.readFile(configPath, 'utf8')).previousHooksPath || '';
            } catch {
                previousHooksPath = '';
            }
        }

        if (previousHooksPath) {
            runGit(['config', 'core.hooksPath', previousHooksPath], repoRoot);
        } else {
            runGit(['config', '--unset', 'core.hooksPath'], repoRoot);
        }
    }

    await fs.rm(managedRoot, { recursive: true, force: true });

    if (!quiet) {
        console.log('worktree-deps-autolink uninstalled');
    }
}

async function printStatus({ cwd } = {}) {
    const targetCwd = cwd || process.cwd();
    if (!isGitWorkTree(targetCwd)) {
        console.log('not inside a Git worktree');
        return;
    }

    const repoRoot = runGit(['rev-parse', '--show-toplevel'], targetCwd);
    const commonGitDir = path.resolve(repoRoot, runGit(['rev-parse', '--git-common-dir'], repoRoot));
    const currentHooksPath = tryGit(['config', '--get', 'core.hooksPath'], repoRoot);
    const hooksDir = path.join(commonGitDir, 'worktree-deps-autolink', '_');

    console.log(`repoRoot=${repoRoot}`);
    console.log(`core.hooksPath=${currentHooksPath || '(default)'}`);
    console.log(`managedHooksPath=${hooksDir}`);
    console.log(`installed=${samePath(resolveHooksPath(currentHooksPath, repoRoot, commonGitDir), hooksDir)}`);
}

module.exports = {
    install,
    uninstall,
    printStatus
};
